# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$julia\
$python\
$line_break\
$character"""

[os]
style = "sky"
disabled = false

[username]
format = '[$user]($style)'
show_always = true
style_user = "bold blue"
style_root = "bold peach"

[hostname]
format = '[@$hostname $ssh_symbol]($style)in '
style = "bold blue"
ssh_only = false
ssh_symbol = " "

[directory]
home_symbol = '🏡'
read_only = " 󰌾"
read_only_style = "red"
truncation_length = 4
truncation_symbol = ".../"
style = "bold pink"

[git_branch]
symbol = " "
style = "bold mauve"

[git_commit]
tag_symbol = '  '

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
disabled = false

[git_status]
style = "bold red"

[c]
symbol = " "
style = "bold yellow"

[julia]
symbol = " "
style = "bold yellow"

[lua]
symbol = " "
style = "bold yellow"

[python]
symbol = " "
style = "bold yellow"

[character]
success_symbol = " [󰄛](green)"
error_symbol = " [󰄛](red)"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
